# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocketIOApp (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocketIOApp (iOS)
  # pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'Socket.IO-Client-Swift', '~> 16.0.1'

end

target 'SocketIOApp (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocketIOApp (macOS)
  pod 'Socket.IO-Client-Swift', '~> 16.0.1'

end
